WaterProject/Models/Cart.cs
using WaterProject.Components;

namespace WaterProject.Models;

public class Cart
{
    public List<CartLine> Lines { get; set; } = new List<CartLine>();

    
    public void AddItem(Project p, int quantity)
    {
        CartLine? line = Lines
            .Where(x => x.Project.ProjectId == p.ProjectId)
            .FirstOrDefault();
        
        // Has this item already been added to the cart
        if (line == null)
        {
            Lines.Add(new CartLine
            {
                Project = p,
                Quantity = quantity
            });
        }
        else
        {
            line.Quantity += quantity;
        }
    }

    public void RemoveLine(Project proj) => Lines.RemoveAll(x => x.Project.ProjectId == proj.ProjectId);

    public void Clear() => Lines.Clear();

    public decimal CalculateTotal() => Lines.Sum(x => 25 * x.Quantity);

    public class CartLine
    {
        public int CartLineId { get; set; }
        public Project Project { get; set; }
        public int Quantity { get; set; }
    }
}

WaterProject/Models/EFWaterRepository.cs
namespace WaterProject.Models;

public class EFWaterRepository : IWaterRepository
{
    private WaterProjectContext _context;
    
    public EFWaterRepository(WaterProjectContext temp)
    {
        _context = temp;
    }

    public IQueryable<Project> Projects => _context.Projects;
}

WaterProject/Models/IWaterRepository.cs
namespace WaterProject.Models;

public interface IWaterRepository
{
    public IQueryable<Project> Projects { get; }
}

WaterProject/Models/Project.cs
using System.ComponentModel.DataAnnotations;

namespace WaterProject.Models;

public class Project
{
    [Key]
    public int ProjectId { get; set; }
    public string ProjectName { get; set; }
    public string ProgramName { get; set; }
    public string ProjectType { get; set; }
    public int ProjectImpact { get; set; }
    public DateTime ProjectInstallation { get; set; }
    public string ProjectPhase { get; set; }
}

WaterProject/Models/ViewModels/PaginationInfo.cs
namespace WaterProject.Models.ViewModels;

public class PaginationInfo
{
    public int TotalItems { get; set; }
    public int ItemsPerPage { get; set; }
    
    public int CurrentPage { get; set; }
    
    public int TotalNumPages => (int)(Math.Ceiling((decimal) TotalItems / ItemsPerPage));
}

WaterProject/Models/ViewModels/ProjectsListViewModel.cs
namespace WaterProject.Models.ViewModels;

public class ProjectsListViewModel
{
    public IQueryable<Project> Projects { get; set; }
    public PaginationInfo PaginationInfo { get; set; } = new PaginationInfo();
    public string? CurrentProjectType { get; set; }
}

WaterProject/Models/WaterProjectContext.cs
using Microsoft.EntityFrameworkCore;

namespace WaterProject.Models;

public class WaterProjectContext : DbContext 
{
    public WaterProjectContext (DbContextOptions<WaterProjectContext> options) : base(options) { }

    public DbSet<Project> Projects { get; set; }
}

WaterProject/Components/ProjectTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WaterProject.Models;

namespace WaterProject.Components;

public class ProjectTypesViewComponent : ViewComponent
{
    private IWaterRepository _repo;
    
    public ProjectTypesViewComponent(IWaterRepository temp)
    {
        _repo = temp;
    }
    
    public IViewComponentResult Invoke()
    {
        ViewBag.SelectedProjectType = RouteData?.Values["projectType"];
        var projectTypes = _repo.Projects
            .Select(x => x.ProjectType)
            .Distinct()
            .OrderBy(x => x);
        
        return View(projectTypes);
    }
}

WaterProject/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WaterProject.Models;
using WaterProject.Models.ViewModels;

namespace WaterProject.Controllers;

public class HomeController : Controller
{
    private IWaterRepository _repo;

    public HomeController(IWaterRepository temp)
    {
        _repo = temp;
    }

    public IActionResult Index(int pageNum, string projectType)
    {
        int pageSize = 2;

        var blah = new ProjectsListViewModel
        {
            Projects = _repo.Projects
                .Where(x => x.ProjectType == projectType || projectType == null)
                .OrderBy(x => x.ProjectName)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),
            
            PaginationInfo = new PaginationInfo
            {
                CurrentPage = pageNum,
                ItemsPerPage = pageSize,
                TotalItems = projectType == null ?  _repo.Projects.Count() : _repo.Projects.Where(x => x.ProjectType == projectType).Count()
            },
            
            CurrentProjectType = projectType
        };
        
        return View(blah);
    }
    
}

WaterProject/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WaterProject.Infrastructure;
using WaterProject.Models;

namespace WaterProject.Pages;

public class CartModel : PageModel
{
    private IWaterRepository _repo;
    
    public CartModel(IWaterRepository temp)
    {
        _repo = temp;
    }
    public Cart? Cart { get; set; }
    public string ReturnUrl { get; set; } = "/";
    
    public void OnGet(string returnUrl)
    {
        ReturnUrl = returnUrl ?? "/";
        Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
    }

    public IActionResult OnPost(int projectId, string returnUrl)
    {
        Project proj = _repo.Projects
            .FirstOrDefault(x => x.ProjectId == projectId);

        if (proj != null)
        {
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.AddItem(proj, 1);
            HttpContext.Session.SetJson("cart", Cart);
        }

        return RedirectToPage(new { returnUrl = returnUrl });
    }

        
}

WaterProject/Pages/Cart.cshtml
@page
@model WaterProject.Pages.CartModel
@{
}

<h2>Your cart</h2>

<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Project Name</th>
        <th>Quantity</th>
        <th class="text-right">Amount</th>
        <th class="text-right">Subtotal</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var l in Model.Cart?.Lines ?? Enumerable.Empty<Cart.CartLine>())
    {
        <tr>
            <td class="text-left">@l.Project.ProgramName</td>
            <td class="text-center">@l.Quantity</td>
            <td class="text-right">$25</td>
            <td class="text-right">@((l.Quantity * 25).ToString("c"))</td>
        </tr>
    }
    </tbody>
    
    <tfoot>
    <tr>
        <td colspan="3" class="text-right">Total:</td>
        <td class="text-right">@Model.Cart?.CalculateTotal().ToString("c")</td>
    </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Donating</a>
</div>

WaterProject/Pages/_CartLayout.cshtml
@{
}

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>The Water Project</title>
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
    </head>
    <body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">THE WATER PROJECT</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
    </body>
</html>

WaterProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model ProjectsListViewModel

<h1>Water Project</h1>

@foreach (Project p in Model.Projects)
{
    <partial name="ProjectSummary" model="p"></partial>
    
}

<div page-model="@Model.PaginationInfo" page-action="Index" page-class-enabled="true" page-class="btn" 
     page-class-normal="btn-outline-dark" page-class-selected="btn-primary"
     page-url-projectType="@Model.CurrentProjectType" class="btn-group pull-right m-1"></div>

WaterProject/Views/Shared/Components/ProjectTypes/Default.cshtml
@model IQueryable<string>

<div class="d-grid gap-2">
    <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index" asp-route-projectType="" asp-route-pageNum="">Home</a>
    
    @foreach (string pt in Model ?? Enumerable.Empty<string>())
    {
        <a class="btn @(pt == ViewBag.SelectedProjectType ? "btn-primary" : "btn-outline-secondary")" asp-controller="Home" asp-action="Index" asp-route-projectType="@pt" asp-route-pageNum="1">@pt</a>
    }
</div>

WaterProject/Views/Shared/ProjectSummary.cshtml
@using WaterProject.Infrastructure
@model Project

<div class="card m-1 p-1">
    <h4>@Model.ProjectName
        <span class="badge rounded-pill bg-primary text-white float-end"><small>@Model.ProjectImpact served</small></span>
    </h4>
    <ul>
        <li>Project Type: @Model.ProjectType</li>
        <li>Regional Program: @Model.ProgramName</li>
        <li>Installation Date: @Model.ProjectInstallation</li>
        <li>Project Phase: @Model.ProjectPhase</li>
    </ul>
    <form id="@Model.ProjectId" method="post" asp-page="/Cart">
        <input type="hidden" asp-for="ProjectId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <button type="submit" class="btn-outline-success btn-sm float-end">Donate</button>
    </form>
</div>

WaterProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WaterProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WaterProject.styles.css" asp-append-version="true"/>
</head>
<body>
<div class="bg-dark text-white p-2">
    <span class="navbar-brand m-lg-2">THE WATER PROJECT</span>
</div>
<div class="row m-1 p-1">
    <div class="col-3">
        <vc:project-types />
    </div>
    <div class="container col-9">
      <main role="main" class="pb-3">
          @RenderBody()
      </main>
    </div>
</div>



<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>